#!/bin/sh
# This post-checkout hook displays the old and new branch names when switching branches

set -e

previous_branch=$(git rev-parse --abbrev-ref @{-1} 2>/dev/null || echo "unknown")
new_branch=$(git symbolic-ref -q --short HEAD)

pushd "$(dirname "$0")/../../.." > /dev/null
BOOTSTRAP_ROOT=$(pwd)

paths=(
    "Carbon.Components/Carbon.Bootstrap"
    "Carbon.Components/Carbon.Common"
    "Carbon.Components/Carbon.Compat"
    "Carbon.Components/Carbon.Modules"
    "Carbon.Components/Carbon.Preloader"
    "Carbon.Components/Carbon.SDK"
    "Carbon.Hooks/Carbon.Hooks.Base"
    "Carbon.Hooks/Carbon.Hooks.Oxide"
    "Carbon.Hooks/Carbon.Hooks.Community"
)

for P in "${paths[@]}"; do
    target_dir="$BOOTSTRAP_ROOT/Carbon.Core/Carbon.Core/$P"

    if [ -d "$target_dir" ]; then
        cd "$target_dir"
        git fetch origin "${new_branch}" || true
		git checkout -b "${new_branch}" "origin/${new_branch}" || true
		git checkout --track "origin/${new_branch}" || true
		git checkout "${new_branch}" || true
		git pull
    else
        echo "Skipping: Directory $target_dir does not exist."
    fi
done

popd > /dev/null
