// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System
{
	internal readonly struct Range : global::System.IEquatable<global::System.Range>
	{
		public Range(global::System.Index start, global::System.Index end)
		{
			Start = start;
			End = end;
		}

		public global::System.Index Start { get; }
		public global::System.Index End { get; }
		public static global::System.Range StartAt(global::System.Index start) => new global::System.Range(start, global::System.Index.End);
		public static global::System.Range EndAt(global::System.Index end) => new global::System.Range(global::System.Index.Start, end);
		public static global::System.Range All => new global::System.Range(global::System.Index.Start, global::System.Index.End);
		public override bool Equals(object? value) => value is global::System.Range range && Equals(range);
		public bool Equals(global::System.Range other) => other.Start.Equals(Start) && other.End.Equals(End);
		public override int GetHashCode() => ((Start.GetHashCode() << 5) + Start.GetHashCode()) ^ End.GetHashCode();
		public override string ToString() => Start.ToString() + ".." + End.ToString();

		public (int Offset, int Length) GetOffsetAndLength(int length)
		{
			var start = Start.IsFromEnd ? length - Start.Value : Start.Value;
			var end = End.IsFromEnd ? length - End.Value : End.Value;
			if ((uint)end > (uint)length || (uint)start > (uint)end)
			{
				throw new global::System.ArgumentOutOfRangeException("length");
			}

			return (start, end - start);
		}
	}
}
