// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System
{
	internal readonly struct Index : global::System.IEquatable<global::System.Index>
	{
		private readonly int _value;

		public Index(int value, bool fromEnd = false)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			_value = fromEnd ? ~value : value;
		}

		private Index(int value)
		{
			_value = value;
		}

		public static global::System.Index Start => new global::System.Index(0);
		public static global::System.Index End => new global::System.Index(~0);
		public int Value => _value < 0 ? ~_value : _value;
		public bool IsFromEnd => _value < 0;

		public static global::System.Index FromStart(int value)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			return new global::System.Index(value);
		}

		public static global::System.Index FromEnd(int value)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			return new global::System.Index(~value);
		}

		public int GetOffset(int length) => IsFromEnd ? length + _value + 1 : _value;
		public override bool Equals(object? value) => value is global::System.Index index && _value == index._value;
		public bool Equals(global::System.Index other) => _value == other._value;
		public override int GetHashCode() => _value;
		public static implicit operator global::System.Index(int value) => FromStart(value);
		public override string ToString() => IsFromEnd ? "^" + Value.ToString() : ((uint)Value).ToString();
	}
}
