global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Text.RegularExpressions;
global using AsmResolver.DotNet;
global using AsmResolver.DotNet.Code.Cil;
global using AsmResolver.DotNet.Signatures;
global using AsmResolver.DotNet.Signatures.Types;
global using AsmResolver.PE.DotNet.Cil;
global using AsmResolver.PE.DotNet.Metadata.Tables.Rows;
global using Carbon;
global using Carbon.Base;
global using Carbon.Components;
global using Carbon.Core;
global using Carbon.Events;
global using Carbon.Extensions;
global using Carbon.Hooks;
global using Carbon.Plugins;
global using Carbon.Pooling;
global using Oxide.Core;
global using Oxide.Core.Configuration;
global using Oxide.Core.Database;
global using Oxide.Core.Libraries;
global using Oxide.Core.Libraries.Covalence;
global using Oxide.Core.Plugins;
global using Oxide.Game.Rust.Libraries;
global using Oxide.Game.Rust.Libraries.Covalence;
global using Oxide.Plugins;
global using UnityEngine;
global using Logger = Carbon.Logger;
global using Timer = Carbon.Plugins.Timer;
global using Random = Oxide.Core.Random;
