using System;
using System.Text;

namespace Carbon.CompilerPolyfills;

internal static class CompilerPolyfillCatalog
{
	private readonly struct Entry(string metadataName, string hintName, string source, bool forceInDesignTime = false)
	{
		public string MetadataName { get; } = metadataName;
		public string HintName { get; } = hintName;
		public string Source { get; } = source;
		public bool ForceInDesignTime { get; } = forceInDesignTime;
	}

	private static readonly Entry[] Entries =
	[
		new("System.Index", "System.Index.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System
{
	public readonly struct Index : global::System.IEquatable<global::System.Index>
	{
		private readonly int _value;

		public Index(int value, bool fromEnd = false)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			_value = fromEnd ? ~value : value;
		}

		private Index(int value)
		{
			_value = value;
		}

		public static global::System.Index Start => new global::System.Index(0);
		public static global::System.Index End => new global::System.Index(~0);
		public int Value => _value < 0 ? ~_value : _value;
		public bool IsFromEnd => _value < 0;

		public static global::System.Index FromStart(int value)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			return new global::System.Index(value);
		}

		public static global::System.Index FromEnd(int value)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			return new global::System.Index(~value);
		}

		public int GetOffset(int length) => IsFromEnd ? length + _value + 1 : _value;
		public override bool Equals(object? value) => value is global::System.Index index && _value == index._value;
		public bool Equals(global::System.Index other) => _value == other._value;
		public override int GetHashCode() => _value;
		public static implicit operator global::System.Index(int value) => FromStart(value);
		public override string ToString() => IsFromEnd ? "^" + Value.ToString() : ((uint)Value).ToString();
	}
}
""", forceInDesignTime: true),
		new("System.Range", "System.Range.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System
{
	public readonly struct Range : global::System.IEquatable<global::System.Range>
	{
		public Range(global::System.Index start, global::System.Index end)
		{
			Start = start;
			End = end;
		}

		public global::System.Index Start { get; }
		public global::System.Index End { get; }
		public static global::System.Range StartAt(global::System.Index start) => new global::System.Range(start, global::System.Index.End);
		public static global::System.Range EndAt(global::System.Index end) => new global::System.Range(global::System.Index.Start, end);
		public static global::System.Range All => new global::System.Range(global::System.Index.Start, global::System.Index.End);
		public override bool Equals(object? value) => value is global::System.Range range && Equals(range);
		public bool Equals(global::System.Range other) => other.Start.Equals(Start) && other.End.Equals(End);
		public override int GetHashCode() => ((Start.GetHashCode() << 5) + Start.GetHashCode()) ^ End.GetHashCode();
		public override string ToString() => Start.ToString() + ".." + End.ToString();

		public (int Offset, int Length) GetOffsetAndLength(int length)
		{
			var start = Start.IsFromEnd ? length - Start.Value : Start.Value;
			var end = End.IsFromEnd ? length - End.Value : End.Value;
			if ((uint)end > (uint)length || (uint)start > (uint)end)
			{
				throw new global::System.ArgumentOutOfRangeException("length");
			}

			return (start, end - start);
		}
	}
}
""", forceInDesignTime: true),
		new("System.Diagnostics.CodeAnalysis.NotNullWhenAttribute", "NotNullWhenAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class NotNullWhenAttribute : global::System.Attribute
	{
		public NotNullWhenAttribute(bool returnValue)
		{
			ReturnValue = returnValue;
		}

		public bool ReturnValue { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute", "MaybeNullWhenAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class MaybeNullWhenAttribute : global::System.Attribute
	{
		public MaybeNullWhenAttribute(bool returnValue)
		{
			ReturnValue = returnValue;
		}

		public bool ReturnValue { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute", "NotNullIfNotNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue, AllowMultiple = true, Inherited = false)]
	public sealed class NotNullIfNotNullAttribute : global::System.Attribute
	{
		public NotNullIfNotNullAttribute(string parameterName)
		{
			ParameterName = parameterName;
		}

		public string ParameterName { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.NotNullAttribute", "NotNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue, Inherited = false)]
	public sealed class NotNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.MaybeNullAttribute", "MaybeNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue, Inherited = false)]
	public sealed class MaybeNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.AllowNullAttribute", "AllowNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class AllowNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DisallowNullAttribute", "DisallowNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class DisallowNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute", "DoesNotReturnAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class DoesNotReturnAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute", "DoesNotReturnIfAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class DoesNotReturnIfAttribute : global::System.Attribute
	{
		public DoesNotReturnIfAttribute(bool parameterValue)
		{
			ParameterValue = parameterValue;
		}

		public bool ParameterValue { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.IsExternalInit", "IsExternalInit.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	public static class IsExternalInit
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute", "CompilerFeatureRequiredAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.All, AllowMultiple = true, Inherited = false)]
	public sealed class CompilerFeatureRequiredAttribute : global::System.Attribute
	{
		public CompilerFeatureRequiredAttribute(string featureName)
		{
			FeatureName = featureName;
		}

		public string FeatureName { get; }
		public bool IsOptional { get; set; }
		public const string RefStructs = nameof(RefStructs);
		public const string RequiredMembers = nameof(RequiredMembers);
	}
}
"""),
		new("System.Runtime.CompilerServices.RequiredMemberAttribute", "RequiredMemberAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(
		global::System.AttributeTargets.Class |
		global::System.AttributeTargets.Struct |
		global::System.AttributeTargets.Field |
		global::System.AttributeTargets.Property,
		AllowMultiple = false,
		Inherited = false)]
	public sealed class RequiredMemberAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute", "SetsRequiredMembersAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
	public sealed class SetsRequiredMembersAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.InterpolatedStringHandlerAttribute", "InterpolatedStringHandlerAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	public sealed class InterpolatedStringHandlerAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.InterpolatedStringHandlerArgumentAttribute", "InterpolatedStringHandlerArgumentAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
	public sealed class InterpolatedStringHandlerArgumentAttribute : global::System.Attribute
	{
		public InterpolatedStringHandlerArgumentAttribute(string argument)
		{
			Arguments = new[] { argument };
		}

		public InterpolatedStringHandlerArgumentAttribute(params string[] arguments)
		{
			Arguments = arguments;
		}

		public string[] Arguments { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.CallerArgumentExpressionAttribute", "CallerArgumentExpressionAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
	public sealed class CallerArgumentExpressionAttribute : global::System.Attribute
	{
		public CallerArgumentExpressionAttribute(string parameterName)
		{
			ParameterName = parameterName;
		}

		public string ParameterName { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.ModuleInitializerAttribute", "ModuleInitializerAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
	public sealed class ModuleInitializerAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.SkipLocalsInitAttribute", "SkipLocalsInitAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Module | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Event, Inherited = false)]
	public sealed class SkipLocalsInitAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.MemberNotNullAttribute", "MemberNotNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
	public sealed class MemberNotNullAttribute : global::System.Attribute
	{
		public MemberNotNullAttribute(string member)
		{
			Members = new[] { member };
		}

		public MemberNotNullAttribute(params string[] members)
		{
			Members = members;
		}

		public string[] Members { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.MemberNotNullWhenAttribute", "MemberNotNullWhenAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
	public sealed class MemberNotNullWhenAttribute : global::System.Attribute
	{
		public MemberNotNullWhenAttribute(bool returnValue, string member)
		{
			ReturnValue = returnValue;
			Members = new[] { member };
		}

		public MemberNotNullWhenAttribute(bool returnValue, params string[] members)
		{
			ReturnValue = returnValue;
			Members = members;
		}

		public bool ReturnValue { get; }
		public string[] Members { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.StringSyntaxAttribute", "StringSyntaxAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class StringSyntaxAttribute : global::System.Attribute
	{
		public StringSyntaxAttribute(string syntax)
		{
			Syntax = syntax;
			Arguments = new object?[0];
		}

		public StringSyntaxAttribute(string syntax, params object?[] arguments)
		{
			Syntax = syntax;
			Arguments = arguments;
		}

		public string Syntax { get; }
		public object?[] Arguments { get; }
		public const string CompositeFormat = nameof(CompositeFormat);
		public const string DateOnlyFormat = nameof(DateOnlyFormat);
		public const string DateTimeFormat = nameof(DateTimeFormat);
		public const string EnumFormat = nameof(EnumFormat);
		public const string GuidFormat = nameof(GuidFormat);
		public const string Json = nameof(Json);
		public const string NumericFormat = nameof(NumericFormat);
		public const string Regex = nameof(Regex);
		public const string TimeOnlyFormat = nameof(TimeOnlyFormat);
		public const string TimeSpanFormat = nameof(TimeSpanFormat);
		public const string Uri = nameof(Uri);
		public const string Xml = nameof(Xml);
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.UnscopedRefAttribute", "UnscopedRefAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class UnscopedRefAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.ConstantExpectedAttribute", "ConstantExpectedAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class ConstantExpectedAttribute : global::System.Attribute
	{
		public object? Min { get; set; }
		public object? Max { get; set; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.ExperimentalAttribute", "ExperimentalAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Module | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Field | global::System.AttributeTargets.Event | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Delegate, Inherited = false)]
	public sealed class ExperimentalAttribute : global::System.Attribute
	{
		public ExperimentalAttribute(string diagnosticId)
		{
			DiagnosticId = diagnosticId;
		}

		public string DiagnosticId { get; }
		public string? UrlFormat { get; set; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes", "DynamicallyAccessedMemberTypes.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.Flags]
	public enum DynamicallyAccessedMemberTypes
	{
		None = 0,
		PublicParameterlessConstructor = 0x0001,
		PublicConstructors = 0x0003,
		NonPublicConstructors = 0x0004,
		PublicMethods = 0x0008,
		NonPublicMethods = 0x0010,
		PublicFields = 0x0020,
		NonPublicFields = 0x0040,
		PublicNestedTypes = 0x0080,
		NonPublicNestedTypes = 0x0100,
		PublicProperties = 0x0200,
		NonPublicProperties = 0x0400,
		PublicEvents = 0x0800,
		NonPublicEvents = 0x1000,
		Interfaces = 0x2000,
		All = ~None
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute", "DynamicallyAccessedMembersAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.ReturnValue | global::System.AttributeTargets.GenericParameter | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.Method | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false)]
	public sealed class DynamicallyAccessedMembersAttribute : global::System.Attribute
	{
		public DynamicallyAccessedMembersAttribute(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes memberTypes)
		{
			MemberTypes = memberTypes;
		}

		public global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes MemberTypes { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute", "DynamicDependencyAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Field | global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
	public sealed class DynamicDependencyAttribute : global::System.Attribute
	{
		public DynamicDependencyAttribute(string memberSignature)
		{
			MemberSignature = memberSignature;
		}

		public DynamicDependencyAttribute(string memberSignature, global::System.Type type)
		{
			MemberSignature = memberSignature;
			Type = type;
		}

		public DynamicDependencyAttribute(string memberSignature, string typeName, string assemblyName)
		{
			MemberSignature = memberSignature;
			TypeName = typeName;
			AssemblyName = assemblyName;
		}

		public DynamicDependencyAttribute(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes memberTypes, global::System.Type type)
		{
			MemberTypes = memberTypes;
			Type = type;
		}

		public DynamicDependencyAttribute(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes memberTypes, string typeName, string assemblyName)
		{
			MemberTypes = memberTypes;
			TypeName = typeName;
			AssemblyName = assemblyName;
		}

		public string? MemberSignature { get; }
		public global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes MemberTypes { get; }
		public global::System.Type? Type { get; }
		public string? TypeName { get; }
		public string? AssemblyName { get; }
		public string? Condition { get; set; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.FeatureGuardAttribute", "FeatureGuardAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class FeatureGuardAttribute : global::System.Attribute
	{
		public FeatureGuardAttribute(global::System.Type featureType)
		{
			FeatureType = featureType;
		}

		public global::System.Type FeatureType { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.FeatureSwitchDefinitionAttribute", "FeatureSwitchDefinitionAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class FeatureSwitchDefinitionAttribute : global::System.Attribute
	{
		public FeatureSwitchDefinitionAttribute(string switchName)
		{
			SwitchName = switchName;
		}

		public string SwitchName { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.RequiresAssemblyFilesAttribute", "RequiresAssemblyFilesAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class RequiresAssemblyFilesAttribute : global::System.Attribute
	{
		public RequiresAssemblyFilesAttribute(string message)
		{
			Message = message;
		}

		public string Message { get; }
		public string? Url { get; set; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute", "RequiresDynamicCodeAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, Inherited = false)]
	public sealed class RequiresDynamicCodeAttribute : global::System.Attribute
	{
		public RequiresDynamicCodeAttribute(string message)
		{
			Message = message;
		}

		public string Message { get; }
		public string? Url { get; set; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.RequiresUnreferencedCodeAttribute", "RequiresUnreferencedCodeAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, Inherited = false)]
	public sealed class RequiresUnreferencedCodeAttribute : global::System.Attribute
	{
		public RequiresUnreferencedCodeAttribute(string message)
		{
			Message = message;
		}

		public string Message { get; }
		public string? Url { get; set; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessageAttribute", "UnconditionalSuppressMessageAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.All, AllowMultiple = true, Inherited = false)]
	public sealed class UnconditionalSuppressMessageAttribute : global::System.Attribute
	{
		public UnconditionalSuppressMessageAttribute(string category, string checkId)
		{
			Category = category;
			CheckId = checkId;
		}

		public string Category { get; }
		public string CheckId { get; }
		public string? Scope { get; set; }
		public string? Target { get; set; }
		public string? MessageId { get; set; }
		public string? Justification { get; set; }
	}
}
"""),
		new("System.Diagnostics.DebuggerDisableUserUnhandledExceptionsAttribute", "DebuggerDisableUserUnhandledExceptionsAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class DebuggerDisableUserUnhandledExceptionsAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.StackTraceHiddenAttribute", "StackTraceHiddenAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Struct, Inherited = false)]
	public sealed class StackTraceHiddenAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.AsyncMethodBuilderAttribute", "AsyncMethodBuilderAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Delegate | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class AsyncMethodBuilderAttribute : global::System.Attribute
	{
		public AsyncMethodBuilderAttribute(global::System.Type builderType)
		{
			BuilderType = builderType;
		}

		public global::System.Type BuilderType { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.CollectionBuilderAttribute", "CollectionBuilderAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface, Inherited = false)]
	public sealed class CollectionBuilderAttribute : global::System.Attribute
	{
		public CollectionBuilderAttribute(global::System.Type builderType, string methodName)
		{
			BuilderType = builderType;
			MethodName = methodName;
		}

		public global::System.Type BuilderType { get; }
		public string MethodName { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute", "DisableRuntimeMarshallingAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, Inherited = false)]
	public sealed class DisableRuntimeMarshallingAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.InlineArrayAttribute", "InlineArrayAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, Inherited = false)]
	public sealed class InlineArrayAttribute : global::System.Attribute
	{
		public InlineArrayAttribute(int length)
		{
			Length = length;
		}

		public int Length { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute", "OverloadResolutionPriorityAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class OverloadResolutionPriorityAttribute : global::System.Attribute
	{
		public OverloadResolutionPriorityAttribute(int priority)
		{
			Priority = priority;
		}

		public int Priority { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.ParamCollectionAttribute", "ParamCollectionAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class ParamCollectionAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.RequiresLocationAttribute", "RequiresLocationAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class RequiresLocationAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.UnsafeAccessorKind", "UnsafeAccessorKind.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	public enum UnsafeAccessorKind
	{
		Constructor,
		Method,
		StaticMethod,
		Field,
		StaticField
	}
}
"""),
		new("System.Runtime.CompilerServices.UnsafeAccessorAttribute", "UnsafeAccessorAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
	public sealed class UnsafeAccessorAttribute : global::System.Attribute
	{
		public UnsafeAccessorAttribute(global::System.Runtime.CompilerServices.UnsafeAccessorKind kind)
		{
			Kind = kind;
		}

		public global::System.Runtime.CompilerServices.UnsafeAccessorKind Kind { get; }
		public string? Name { get; set; }
	}
}
"""),
		new("System.Runtime.InteropServices.SuppressGCTransitionAttribute", "SuppressGCTransitionAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.InteropServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class SuppressGCTransitionAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute", "UnmanagedCallersOnlyAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.InteropServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class UnmanagedCallersOnlyAttribute : global::System.Attribute
	{
		public global::System.Type[]? CallConvs { get; set; }
		public string? EntryPoint { get; set; }
	}
}
"""),
		new("System.Runtime.InteropServices.WasmImportLinkageAttribute", "WasmImportLinkageAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.InteropServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class WasmImportLinkageAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.Versioning.ObsoletedOSPlatformAttribute", "ObsoletedOSPlatformAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Class | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Event | global::System.AttributeTargets.Field | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Method | global::System.AttributeTargets.Module | global::System.AttributeTargets.Property | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
	public sealed class ObsoletedOSPlatformAttribute : global::System.Attribute
	{
		public ObsoletedOSPlatformAttribute(string platformName)
		{
			PlatformName = platformName;
		}

		public string PlatformName { get; }
		public string? Message { get; set; }
		public string? Url { get; set; }
	}
}
"""),
		new("System.Runtime.Versioning.SupportedOSPlatformAttribute", "SupportedOSPlatformAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Class | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Event | global::System.AttributeTargets.Field | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Method | global::System.AttributeTargets.Module | global::System.AttributeTargets.Property | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
	public sealed class SupportedOSPlatformAttribute : global::System.Attribute
	{
		public SupportedOSPlatformAttribute(string platformName)
		{
			PlatformName = platformName;
		}

		public string PlatformName { get; }
	}
}
"""),
		new("System.Runtime.Versioning.SupportedOSPlatformGuardAttribute", "SupportedOSPlatformGuardAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
	public sealed class SupportedOSPlatformGuardAttribute : global::System.Attribute
	{
		public SupportedOSPlatformGuardAttribute(string platformName)
		{
			PlatformName = platformName;
		}

		public string PlatformName { get; }
	}
}
"""),
		new("System.Runtime.Versioning.TargetPlatformAttribute", "TargetPlatformAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
	public sealed class TargetPlatformAttribute : global::System.Attribute
	{
		public TargetPlatformAttribute(string platformName)
		{
			PlatformName = platformName;
		}

		public string PlatformName { get; }
	}
}
"""),
		new("System.Runtime.Versioning.UnsupportedOSPlatformAttribute", "UnsupportedOSPlatformAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Class | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Event | global::System.AttributeTargets.Field | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Method | global::System.AttributeTargets.Module | global::System.AttributeTargets.Property | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
	public sealed class UnsupportedOSPlatformAttribute : global::System.Attribute
	{
		public UnsupportedOSPlatformAttribute(string platformName)
		{
			PlatformName = platformName;
		}

		public string PlatformName { get; }
		public string? Message { get; set; }
		public string? Url { get; set; }
	}
}
"""),
		new("System.Runtime.Versioning.UnsupportedOSPlatformGuardAttribute", "UnsupportedOSPlatformGuardAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
	public sealed class UnsupportedOSPlatformGuardAttribute : global::System.Attribute
	{
		public UnsupportedOSPlatformGuardAttribute(string platformName)
		{
			PlatformName = platformName;
		}

		public string PlatformName { get; }
	}
}
"""),
		new("System.Runtime.Versioning.RequiresPreviewFeaturesAttribute", "RequiresPreviewFeaturesAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.Versioning
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Assembly | global::System.AttributeTargets.Module | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Enum | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Field | global::System.AttributeTargets.Event | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Delegate, Inherited = false)]
	public sealed class RequiresPreviewFeaturesAttribute : global::System.Attribute
	{
		public RequiresPreviewFeaturesAttribute()
		{
		}

		public RequiresPreviewFeaturesAttribute(string? message)
		{
			Message = message;
		}

		public string? Message { get; }
		public string? Url { get; set; }
	}
}
""")
	];

	public static string BuildSource(Func<string, bool> typeExists, bool forceDesignTimePolyfills, string accessibility = "public")
	{
		var source = new StringBuilder();

		foreach (var entry in Entries)
		{
			if (!forceDesignTimePolyfills || !entry.ForceInDesignTime)
			{
				if (typeExists(entry.MetadataName))
				{
					continue;
				}
			}

			source.AppendLine(accessibility == "public" ? entry.Source : WithAccessibility(entry.Source, accessibility));
		}

		return source.ToString();
	}

	private static string WithAccessibility(string source, string accessibility)
	{
		return source
			.Replace("\tpublic readonly struct ", $"\t{accessibility} readonly struct ")
			.Replace("\tpublic enum ", $"\t{accessibility} enum ")
			.Replace("\tpublic static class ", $"\t{accessibility} static class ")
			.Replace("\tpublic sealed class ", $"\t{accessibility} sealed class ");
	}
}
