using System;
using System.Text;

namespace Carbon.CompilerPolyfills;

internal static class CompilerPolyfillCatalog
{
	private readonly struct Entry(string metadataName, string hintName, string source, bool forceInDesignTime = false)
	{
		public string MetadataName { get; } = metadataName;
		public string HintName { get; } = hintName;
		public string Source { get; } = source;
		public bool ForceInDesignTime { get; } = forceInDesignTime;
	}

	private static readonly Entry[] Entries =
	[
		new("System.Index", "System.Index.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System
{
	public readonly struct Index : global::System.IEquatable<global::System.Index>
	{
		private readonly int _value;

		public Index(int value, bool fromEnd = false)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			_value = fromEnd ? ~value : value;
		}

		private Index(int value)
		{
			_value = value;
		}

		public static global::System.Index Start => new global::System.Index(0);
		public static global::System.Index End => new global::System.Index(~0);
		public int Value => _value < 0 ? ~_value : _value;
		public bool IsFromEnd => _value < 0;

		public static global::System.Index FromStart(int value)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			return new global::System.Index(value);
		}

		public static global::System.Index FromEnd(int value)
		{
			if (value < 0)
			{
				throw new global::System.ArgumentOutOfRangeException("value", "Non-negative number required.");
			}

			return new global::System.Index(~value);
		}

		public int GetOffset(int length) => IsFromEnd ? length + _value + 1 : _value;
		public override bool Equals(object? value) => value is global::System.Index index && _value == index._value;
		public bool Equals(global::System.Index other) => _value == other._value;
		public override int GetHashCode() => _value;
		public static implicit operator global::System.Index(int value) => FromStart(value);
		public override string ToString() => IsFromEnd ? "^" + Value.ToString() : ((uint)Value).ToString();
	}
}
""", forceInDesignTime: true),
		new("System.Range", "System.Range.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System
{
	public readonly struct Range : global::System.IEquatable<global::System.Range>
	{
		public Range(global::System.Index start, global::System.Index end)
		{
			Start = start;
			End = end;
		}

		public global::System.Index Start { get; }
		public global::System.Index End { get; }
		public static global::System.Range StartAt(global::System.Index start) => new global::System.Range(start, global::System.Index.End);
		public static global::System.Range EndAt(global::System.Index end) => new global::System.Range(global::System.Index.Start, end);
		public static global::System.Range All => new global::System.Range(global::System.Index.Start, global::System.Index.End);
		public override bool Equals(object? value) => value is global::System.Range range && Equals(range);
		public bool Equals(global::System.Range other) => other.Start.Equals(Start) && other.End.Equals(End);
		public override int GetHashCode() => ((Start.GetHashCode() << 5) + Start.GetHashCode()) ^ End.GetHashCode();
		public override string ToString() => Start.ToString() + ".." + End.ToString();

		public (int Offset, int Length) GetOffsetAndLength(int length)
		{
			var start = Start.IsFromEnd ? length - Start.Value : Start.Value;
			var end = End.IsFromEnd ? length - End.Value : End.Value;
			if ((uint)end > (uint)length || (uint)start > (uint)end)
			{
				throw new global::System.ArgumentOutOfRangeException("length");
			}

			return (start, end - start);
		}
	}
}
""", forceInDesignTime: true),
		new("System.Diagnostics.CodeAnalysis.NotNullWhenAttribute", "NotNullWhenAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class NotNullWhenAttribute : global::System.Attribute
	{
		public NotNullWhenAttribute(bool returnValue)
		{
			ReturnValue = returnValue;
		}

		public bool ReturnValue { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute", "MaybeNullWhenAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class MaybeNullWhenAttribute : global::System.Attribute
	{
		public MaybeNullWhenAttribute(bool returnValue)
		{
			ReturnValue = returnValue;
		}

		public bool ReturnValue { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute", "NotNullIfNotNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue, AllowMultiple = true, Inherited = false)]
	public sealed class NotNullIfNotNullAttribute : global::System.Attribute
	{
		public NotNullIfNotNullAttribute(string parameterName)
		{
			ParameterName = parameterName;
		}

		public string ParameterName { get; }
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.NotNullAttribute", "NotNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue, Inherited = false)]
	public sealed class NotNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.MaybeNullAttribute", "MaybeNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue, Inherited = false)]
	public sealed class MaybeNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.AllowNullAttribute", "AllowNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class AllowNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DisallowNullAttribute", "DisallowNullAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, Inherited = false)]
	public sealed class DisallowNullAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute", "DoesNotReturnAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
	public sealed class DoesNotReturnAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute", "DoesNotReturnIfAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
	public sealed class DoesNotReturnIfAttribute : global::System.Attribute
	{
		public DoesNotReturnIfAttribute(bool parameterValue)
		{
			ParameterValue = parameterValue;
		}

		public bool ParameterValue { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.IsExternalInit", "IsExternalInit.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	public static class IsExternalInit
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute", "CompilerFeatureRequiredAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.All, AllowMultiple = true, Inherited = false)]
	public sealed class CompilerFeatureRequiredAttribute : global::System.Attribute
	{
		public CompilerFeatureRequiredAttribute(string featureName)
		{
			FeatureName = featureName;
		}

		public string FeatureName { get; }
		public bool IsOptional { get; set; }
		public const string RefStructs = nameof(RefStructs);
		public const string RequiredMembers = nameof(RequiredMembers);
	}
}
"""),
		new("System.Runtime.CompilerServices.RequiredMemberAttribute", "RequiredMemberAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(
		global::System.AttributeTargets.Class |
		global::System.AttributeTargets.Struct |
		global::System.AttributeTargets.Field |
		global::System.AttributeTargets.Property,
		AllowMultiple = false,
		Inherited = false)]
	public sealed class RequiredMemberAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute", "SetsRequiredMembersAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
	public sealed class SetsRequiredMembersAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.InterpolatedStringHandlerAttribute", "InterpolatedStringHandlerAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	public sealed class InterpolatedStringHandlerAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.InterpolatedStringHandlerArgumentAttribute", "InterpolatedStringHandlerArgumentAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
	public sealed class InterpolatedStringHandlerArgumentAttribute : global::System.Attribute
	{
		public InterpolatedStringHandlerArgumentAttribute(string argument)
		{
			Arguments = new[] { argument };
		}

		public InterpolatedStringHandlerArgumentAttribute(params string[] arguments)
		{
			Arguments = arguments;
		}

		public string[] Arguments { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.CallerArgumentExpressionAttribute", "CallerArgumentExpressionAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
	public sealed class CallerArgumentExpressionAttribute : global::System.Attribute
	{
		public CallerArgumentExpressionAttribute(string parameterName)
		{
			ParameterName = parameterName;
		}

		public string ParameterName { get; }
	}
}
"""),
		new("System.Runtime.CompilerServices.ModuleInitializerAttribute", "ModuleInitializerAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
	public sealed class ModuleInitializerAttribute : global::System.Attribute
	{
	}
}
"""),
		new("System.Runtime.CompilerServices.SkipLocalsInitAttribute", "SkipLocalsInitAttribute.g.cs", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Module | global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Constructor | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Event, Inherited = false)]
	public sealed class SkipLocalsInitAttribute : global::System.Attribute
	{
	}
}
""")
	];

	public static string BuildSource(Func<string, bool> typeExists, bool forceDesignTimePolyfills, string accessibility = "public")
	{
		var source = new StringBuilder();

		foreach (var entry in Entries)
		{
			if (!forceDesignTimePolyfills || !entry.ForceInDesignTime)
			{
				if (typeExists(entry.MetadataName))
				{
					continue;
				}
			}

			source.AppendLine(accessibility == "public" ? entry.Source : WithAccessibility(entry.Source, accessibility));
		}

		return source.ToString();
	}

	private static string WithAccessibility(string source, string accessibility)
	{
		return source
			.Replace("\tpublic readonly struct ", $"\t{accessibility} readonly struct ")
			.Replace("\tpublic static class ", $"\t{accessibility} static class ")
			.Replace("\tpublic sealed class ", $"\t{accessibility} sealed class ");
	}
}
