using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Carbon.SourceGenerators;

[Generator]
public sealed class InternalCallHookGenerator : IIncrementalGenerator
{
	private const string BaseModuleType = "Carbon.Base.BaseModule";
	private const string CarbonPluginType = "Carbon.Plugins.CarbonPlugin";
	private const string HookMethodAttributeType = "Oxide.Core.Plugins.HookMethodAttribute";
	private const string ConditionalAttributeType = "Carbon.ConditionalAttribute";

	private static readonly SymbolDisplayFormat TypeFormat = new(
		SymbolDisplayGlobalNamespaceStyle.Included,
		SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
		SymbolDisplayGenericsOptions.IncludeTypeParameters,
		miscellaneousOptions:
		SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
		SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var targetTypes = context.SyntaxProvider
			.CreateSyntaxProvider(static (node, _) => IsCandidate(node), static (ctx, ct) => GetTargetType(ctx, ct))
			.Where(static symbol => symbol is not null)
			.Collect();

		context.RegisterSourceOutput(targetTypes, static (sourceContext, symbols) => Emit(sourceContext, symbols));
	}

	private static bool IsCandidate(SyntaxNode node)
	{
		return node is ClassDeclarationSyntax classDeclaration &&
		       classDeclaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
	}

	private static INamedTypeSymbol? GetTargetType(GeneratorSyntaxContext context, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();

		if (context.Node is not ClassDeclarationSyntax classDeclaration)
		{
			return null;
		}

		if (ModelExtensions.GetDeclaredSymbol(context.SemanticModel, classDeclaration, cancellationToken) is not INamedTypeSymbol typeSymbol)
		{
			return null;
		}

		if (typeSymbol.TypeKind != TypeKind.Class)
		{
			return null;
		}

		if (!DerivesFrom(typeSymbol, BaseModuleType) && !DerivesFrom(typeSymbol, CarbonPluginType))
		{
			return null;
		}

		if (HasInternalCallHookOverride(typeSymbol))
		{
			return null;
		}

		return typeSymbol;
	}

	private static void Emit(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> symbols)
	{
		var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

		foreach (var symbol in symbols)
		{
			if (symbol is null || !seen.Add(symbol))
			{
				continue;
			}

			var methods = GetHookMethods(symbol);
			if (methods.Count == 0)
			{
				continue;
			}

			var source = BuildSource(symbol, methods);
			var hintName = $"{SanitizeHintName(symbol.ToDisplayString())}.InternalCallHook.g.cs";
			context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
		}
	}

	private static List<IMethodSymbol> GetHookMethods(INamedTypeSymbol typeSymbol)
	{
		return typeSymbol.GetMembers()
			.OfType<IMethodSymbol>()
			.Where(static method =>
				method.MethodKind == MethodKind.Ordinary &&
				!method.IsImplicitlyDeclared &&
				!method.IsStatic &&
				method.TypeParameters.Length == 0 &&
				(method.DeclaredAccessibility != Accessibility.Public || HasAttribute(method, HookMethodAttributeType)) &&
				method.Name != "InternalCallHook")
			.OrderBy(static method => ResolveHookName(method), StringComparer.Ordinal)
			.ThenBy(static method => method.Name, StringComparer.Ordinal)
			.ToList();
	}

	private static string BuildSource(INamedTypeSymbol typeSymbol, List<IMethodSymbol> methods)
	{
		var builder = new StringBuilder();
		var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace ? null : typeSymbol.ContainingNamespace.ToDisplayString();
		var baseName = DerivesFrom(typeSymbol, BaseModuleType) ? "module" : "plugin";
		var versionOwner = baseName == "plugin" ? "base" : "this";

		var groups = methods
			.GroupBy(ResolveHookName, StringComparer.Ordinal)
			.OrderBy(static group => group.Key, StringComparer.Ordinal)
			.Select(static group => new HookGroup(group.Key, ComputeHookId(group.Key), group.ToList()))
			.ToList();

		var maxArgs = groups.Count == 0 ? 0 : groups.Max(static group => group.Methods.Max(static method => method.Parameters.Length));

		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable disable");
		builder.AppendLine();

		if (!string.IsNullOrEmpty(namespaceName))
		{
			builder.Append("namespace ").Append(namespaceName).AppendLine();
			builder.AppendLine("{");
		}

		builder.Append("partial class ").Append(typeSymbol.Name).AppendLine();
		builder.AppendLine("{");
		builder.AppendLine("\tpublic override object InternalCallHook(uint hook, object[] args)");
		builder.AppendLine("\t{");
		builder.AppendLine("\t\tvar length = args?.Length;");

		for (var index = 0; index < maxArgs; index++)
		{
			builder.Append("\t\tvar narg").Append(index).Append(" = length > ").Append(index).Append(" ? args[").Append(index).AppendLine("] : null;");
		}

		builder.AppendLine("\t\ttry");
		builder.AppendLine("\t\t{");
		builder.AppendLine("\t\t\tswitch (hook)");
		builder.AppendLine("\t\t\t{");

		foreach (var group in groups)
		{
			builder.Append("\t\t\t\t// ").Append(group.Name).Append(" aka ").Append(group.Id).AppendLine();
			builder.Append("\t\t\t\tcase ").Append(group.Id).AppendLine(":");
			builder.AppendLine("\t\t\t\t{");

			var orderedMethods = group.Methods
				.Select(static method => new ScoredMethod(method, GetMethodParameterDepthScore(method)))
				.OrderByDescending(static item => item.Score)
				.ThenBy(static item => item.Method.Name, StringComparer.Ordinal)
				.ToList();

			for (var overloadIndex = 0; overloadIndex < orderedMethods.Count; overloadIndex++)
			{
				AppendMethodInvocation(builder, orderedMethods[overloadIndex].Method, overloadIndex);
			}

			builder.AppendLine("\t\t\t\t\tbreak;");
			builder.AppendLine("\t\t\t\t}");
		}

		builder.AppendLine("\t\t\t}");
		builder.AppendLine("\t\t}");
		builder.AppendLine("\t\tcatch (global::System.Exception ex)");
		builder.AppendLine("\t\t{");
		builder.Append("\t\t\tglobal::Carbon.Logger.Error(string.Format(\"Failed to call internal hook '{0}' on ")
			.Append(baseName)
			.Append(" '{1} v{2}' [{3}]\", global::Carbon.Pooling.HookStringPool.GetOrAdd(hook), ")
			.Append(versionOwner)
			.Append(".Name, ")
			.Append(versionOwner)
			.AppendLine(".Version, hook), ex);");
		builder.AppendLine("\t\t\tOnException(hook);");
		builder.AppendLine("\t\t}");
		builder.AppendLine("\t\treturn null;");
		builder.AppendLine("\t}");
		builder.AppendLine("}");

		if (!string.IsNullOrEmpty(namespaceName))
		{
			builder.AppendLine("}");
		}

		return builder.ToString();
	}

	private static void AppendMethodInvocation(StringBuilder builder, IMethodSymbol method, int overloadIndex)
	{
		var conditionalSymbol = GetConditionalSymbol(method);
		if (!string.IsNullOrWhiteSpace(conditionalSymbol))
		{
			builder.Append("#if ").AppendLine(conditionalSymbol);
		}

		var conditions = new List<string>(method.Parameters.Length);
		var arguments = new List<string>(method.Parameters.Length);

		for (var parameterIndex = 0; parameterIndex < method.Parameters.Length; parameterIndex++)
		{
			var parameter = method.Parameters[parameterIndex];
			var variableName = $"arg{parameterIndex}_{overloadIndex}";
			var guardName = $"narg{parameterIndex}_{overloadIndex}";
			var typeName = parameter.Type.ToDisplayString(TypeFormat);

			if (parameter.RefKind == RefKind.Out)
			{
				arguments.Add($"out var {variableName}");
				continue;
			}

			builder.Append("\t\t\t\t\tvar ").Append(guardName).Append(" = narg").Append(parameterIndex).Append(" is ").Append(typeName)
				.AppendLine(" or null;");
			builder.Append("\t\t\t\t\tvar ").Append(variableName).Append(" = ").Append(guardName).Append(" ? (").Append(typeName).Append(")(narg")
				.Append(parameterIndex).Append(" ?? (").Append(typeName).Append(")default) : (").Append(typeName).AppendLine(")default;");
			conditions.Add(guardName);

			arguments.Add(parameter.RefKind == RefKind.Ref ? $"ref {variableName}" : variableName);
		}

		if (conditions.Count > 0)
		{
			builder.Append("\t\t\t\t\tif (").Append(string.Join(" && ", conditions)).AppendLine(")");
			builder.AppendLine("\t\t\t\t\t{");
		}

		builder.Append("\t\t\t\t\t\t");
		if (method.ReturnsVoid)
		{
			builder.Append(method.Name).Append('(').Append(string.Join(", ", arguments)).AppendLine(");");
		}
		else
		{
			builder.Append("return ").Append(method.Name).Append('(').Append(string.Join(", ", arguments)).AppendLine(");");
		}

		for (var parameterIndex = 0; parameterIndex < method.Parameters.Length; parameterIndex++)
		{
			var parameter = method.Parameters[parameterIndex];
			if (parameter.RefKind is not (RefKind.Ref or RefKind.Out))
			{
				continue;
			}

			builder.Append("\t\t\t\t\t\targs[").Append(parameterIndex).Append("] = arg").Append(parameterIndex).Append('_').Append(overloadIndex)
				.AppendLine(";");
		}

		if (method.ReturnsVoid)
		{
			builder.AppendLine("\t\t\t\t\t\treturn null;");
		}

		if (conditions.Count > 0)
		{
			builder.AppendLine("\t\t\t\t\t}");
		}

		if (!string.IsNullOrWhiteSpace(conditionalSymbol))
		{
			builder.AppendLine("#endif");
		}
	}

	private static bool HasInternalCallHookOverride(INamedTypeSymbol typeSymbol)
	{
		return typeSymbol.GetMembers("InternalCallHook")
			.OfType<IMethodSymbol>()
			.Any(static method =>
				method.MethodKind == MethodKind.Ordinary &&
				method.Parameters.Length == 2 &&
				method.IsOverride);
	}

	private static bool DerivesFrom(INamedTypeSymbol typeSymbol, string fullyQualifiedBaseType)
	{
		for (var current = typeSymbol; current is not null; current = current.BaseType)
		{
			if (current.ToDisplayString() == fullyQualifiedBaseType)
			{
				return true;
			}
		}

		return false;
	}

	private static bool HasAttribute(IMethodSymbol method, string fullyQualifiedAttributeType)
	{
		return method.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == fullyQualifiedAttributeType);
	}

	private static string ResolveHookName(IMethodSymbol method)
	{
		var attribute = method.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == HookMethodAttributeType);
		if (attribute is null)
		{
			return method.Name;
		}

		if (attribute.ConstructorArguments.Length > 0 &&
		    attribute.ConstructorArguments[0].Value is string constructorValue &&
		    !string.IsNullOrWhiteSpace(constructorValue))
		{
			return constructorValue;
		}

		foreach (var argument in attribute.NamedArguments)
		{
			if (argument is { Key: "Name", Value.Value: string namedValue } && !string.IsNullOrWhiteSpace(namedValue))
			{
				return namedValue;
			}
		}

		return method.Name;
	}

	private static string? GetConditionalSymbol(IMethodSymbol method)
	{
		var attribute = method.GetAttributes().FirstOrDefault(current => current.AttributeClass?.ToDisplayString() == ConditionalAttributeType);
		if (attribute is null)
		{
			return null;
		}

		if (attribute.ConstructorArguments.Length > 0 &&
		    attribute.ConstructorArguments[0].Value is string constructorValue &&
		    !string.IsNullOrWhiteSpace(constructorValue))
		{
			return constructorValue;
		}

		foreach (var argument in attribute.NamedArguments)
		{
			if (argument is { Key: "Symbol", Value.Value: string namedValue } && !string.IsNullOrWhiteSpace(namedValue))
			{
				return namedValue;
			}
		}

		return null;
	}

	private static int GetMethodParameterDepthScore(IMethodSymbol method)
	{
		var score = 0;
		foreach (var parameter in method.Parameters)
		{
			score += GetInheritanceDepth(parameter.Type);
		}

		return score;
	}

	private static int GetInheritanceDepth(ITypeSymbol typeSymbol)
	{
		var depth = 0;
		for (var current = typeSymbol.BaseType; current is not null; current = current.BaseType)
		{
			depth++;
		}

		return depth;
	}

	private static uint ComputeHookId(string hookName)
	{
		if (string.IsNullOrEmpty(hookName))
		{
			return 0;
		}

		using var md5 = MD5.Create();
		return BitConverter.ToUInt32(md5.ComputeHash(Encoding.UTF8.GetBytes(hookName)), 0);
	}

	private static string SanitizeHintName(string input)
	{
		var builder = new StringBuilder(input.Length);
		foreach (var character in input)
		{
			builder.Append(char.IsLetterOrDigit(character) ? character : '_');
		}

		return builder.ToString();
	}

	private sealed class HookGroup
	{
		public HookGroup(string name, uint id, List<IMethodSymbol> methods)
		{
			Name = name;
			Id = id;
			Methods = methods;
		}

		public string Name { get; }
		public uint Id { get; }
		public List<IMethodSymbol> Methods { get; }
	}

	private sealed class ScoredMethod
	{
		public ScoredMethod(IMethodSymbol method, int score)
		{
			Method = method;
			Score = score;
		}

		public IMethodSymbol Method { get; }
		public int Score { get; }
	}
}
