//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carbon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carbon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;shortSHA&quot;: &quot;8fb9e7b&quot;,
        ///  &quot;longSHA&quot;: &quot;8fb9e7b952e2e7996d7eab68f1bc4bffef2bc71a&quot;,
        ///  &quot;changeset&quot;: &quot;409&quot;,
        ///  &quot;author_name&quot;: &quot;Joao Brazio&quot;,
        ///  &quot;author_email&quot;: &quot;jbrazio@gmail.com&quot;,
        ///  &quot;date&quot;: &quot;Tue, 27 Sep 2022 11:39:14&quot;,
        ///  &quot;branch&quot;: &quot;rework/sql_perms&quot;,
        ///  &quot;tag&quot;: null,
        ///  &quot;tags&quot;: [],
        ///  &quot;message&quot;: &quot;fix boo boo on daily build action&quot;,
        ///  &quot;repository_name&quot;: &quot;Carbon.Core&quot;,
        ///  &quot;changes&quot;: [
        ///    {
        ///      &quot;path&quot;: &quot;.github/workflows/develop-build.yml&quot;,
        ///      &quot;type&quot;: 1
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string git {
            get {
                return ResourceManager.GetString("git", resourceCulture);
            }
        }
    }
}
