using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Carbon.Jobs;

internal static class ScriptCompilerPolyfills
{
	private static readonly (string MetadataName, string Source)[] Polyfills =
	[
		("System.Runtime.CompilerServices.IsExternalInit", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	/// <summary>
	/// Reserved to be used by the compiler for tracking metadata.
	/// This class should not be used by developers in source code.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public static class IsExternalInit
	{
	}
}
"""),
		("System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	/// <summary>
	/// Indicates that compiler support for a particular feature is required for the location where this attribute is applied.
	/// </summary>
	[global::System.AttributeUsage(global::System.AttributeTargets.All, AllowMultiple = true, Inherited = false)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public sealed class CompilerFeatureRequiredAttribute : global::System.Attribute
	{
		/// <summary>
		/// Creates a new instance of the <see cref="global::System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute"/> type.
		/// </summary>
		/// <param name="featureName">The name of the feature to indicate.</param>
		public CompilerFeatureRequiredAttribute(string featureName)
		{
			FeatureName = featureName;
		}

		/// <summary>
		/// The name of the compiler feature.
		/// </summary>
		public string FeatureName { get; }

		/// <summary>
		/// If true, the compiler can choose to allow access to the location where this attribute is applied if it does not understand <see cref="FeatureName"/>.
		/// </summary>
		public bool IsOptional { get; set; }

		/// <summary>
		/// The <see cref="FeatureName"/> used for the ref structs C# feature.
		/// </summary>
		public const string RefStructs = nameof(RefStructs);

		/// <summary>
		/// The <see cref="FeatureName"/> used for the required members C# feature.
		/// </summary>
		public const string RequiredMembers = nameof(RequiredMembers);
	}
}
"""),
		("System.Runtime.CompilerServices.RequiredMemberAttribute", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Runtime.CompilerServices
{
	/// <summary>
	/// Specifies that a type has required members or that a member is required.
	/// </summary>
	[global::System.AttributeUsage(
		global::System.AttributeTargets.Class |
		global::System.AttributeTargets.Struct |
		global::System.AttributeTargets.Field |
		global::System.AttributeTargets.Property,
		AllowMultiple = false,
		Inherited = false)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public sealed class RequiredMemberAttribute : global::System.Attribute
	{
	}
}
"""),
		("System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute", """
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace System.Diagnostics.CodeAnalysis
{
	/// <summary>
	/// Specifies that this constructor sets all required members for the current type,
	/// and callers do not need to set any required members themselves.
	/// </summary>
	[global::System.AttributeUsage(global::System.AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	public sealed class SetsRequiredMembersAttribute : global::System.Attribute
	{
	}
}
""")
	];

	public static void InjectMissingPolyfills(List<SyntaxTree> trees, IReadOnlyCollection<MetadataReference> references, CSharpParseOptions parseOptions)
	{
		var probeCompilation = CSharpCompilation.Create("__CarbonPolyfillProbe", references: references);
		var source = new StringBuilder();

		foreach (var (metadataName, src) in Polyfills)
		{
			if (probeCompilation.GetTypeByMetadataName(metadataName) != null)
			{
				continue;
			}

			source.AppendLine(src);
		}

		if (source.Length == 0)
		{
			return;
		}

		trees.Insert(0, CSharpSyntaxTree.ParseText(source.ToString(), parseOptions, "__Carbon.CompilerPolyfills.g.cs", Encoding.UTF8));
	}
}
