using System.Text;

namespace Carbon.InternalCallHookGeneration;

public sealed class InternalCallHookTypeModel
{
	public string NamespaceName { get; set; } = string.Empty;
	public string TypeName { get; set; } = string.Empty;
	public string BaseKind { get; set; } = string.Empty;
	public string VersionOwnerExpression { get; set; } = string.Empty;
	public List<string> GlobalUsings { get; } = [];
	public List<string> NamespaceUsings { get; } = [];
	public List<InternalCallHookMethodModel> Methods { get; } = [];
}

public sealed class InternalCallHookMethodModel
{
	public string MethodName { get; set; } = string.Empty;
	public string HookName { get; set; } = string.Empty;
	public uint HookId { get; set; }
	public bool ReturnsVoid { get; set; }
	public int Score { get; set; }
	public string ConditionalSymbol { get; set; } = string.Empty;
	public List<InternalCallHookParameterModel> Parameters { get; } = [];
}

public sealed class InternalCallHookParameterModel
{
	public string TypeName { get; set; } = string.Empty;
	public bool IsOut { get; set; }
	public bool IsRef { get; set; }
	public bool UseInlineDefaultExpression { get; set; }
	public bool RequiresGuard { get; set; }
}

public static class InternalCallHookEmitter
{
	public static string BuildSource(InternalCallHookTypeModel model)
	{
		var builder = new StringBuilder();
		var globalUsings = model.GlobalUsings
			.Select(NormalizeUsing)
			.Where(static item => !string.IsNullOrWhiteSpace(item))
			.Distinct(StringComparer.Ordinal)
			.OrderBy(static item => item, StringComparer.Ordinal)
			.ToList();
		var namespaceUsings = model.NamespaceUsings
			.Select(NormalizeUsing)
			.Where(static item => !string.IsNullOrWhiteSpace(item))
			.Distinct(StringComparer.Ordinal)
			.OrderBy(static item => item, StringComparer.Ordinal)
			.ToList();

		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable disable");

		if (globalUsings.Count > 0)
		{
			builder.AppendLine();
			foreach (var item in globalUsings)
			{
				builder.Append("using ").Append(item).AppendLine(";");
			}
		}

		builder.AppendLine();

		if (!string.IsNullOrWhiteSpace(model.NamespaceName))
		{
			builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
			builder.AppendLine("{");

			foreach (var item in namespaceUsings)
			{
				builder.Append('\t').Append("using ").Append(item).AppendLine(";");
			}

			if (namespaceUsings.Count > 0)
			{
				builder.AppendLine();
			}

			AppendClass(builder, model, 1);
			builder.AppendLine("}");
		}
		else
		{
			AppendClass(builder, model, 0);
		}

		return builder.ToString();
	}

	private static void AppendClass(StringBuilder builder, InternalCallHookTypeModel model, int indent)
	{
		AppendLine(builder, indent, $"partial class {model.TypeName}");
		AppendLine(builder, indent, "{");
		AppendLine(builder, indent + 1, "public override object InternalCallHook(uint hook, object[] args)");
		AppendLine(builder, indent + 1, "{");
		AppendLine(builder, indent + 2, "var length = args?.Length;");

		var maxArgs = model.Methods.Count == 0 ? 0 : model.Methods.Max(static method => method.Parameters.Count);
		for (var parameterIndex = 0; parameterIndex < maxArgs; parameterIndex++)
		{
			AppendLine(builder, indent + 2, $"var narg{parameterIndex} = length > {parameterIndex} ? args[{parameterIndex}] : null;");
		}

		AppendLine(builder, indent + 2, "try");
		AppendLine(builder, indent + 2, "{");
		AppendLine(builder, indent + 3, "switch (hook)");
		AppendLine(builder, indent + 3, "{");

		var groups = model.Methods
			.GroupBy(static method => new { method.HookId, method.HookName })
			.OrderBy(static group => group.Key.HookName, StringComparer.Ordinal)
			.ToList();

		foreach (var group in groups)
		{
			AppendLine(builder, indent + 4, $"// {group.Key.HookName} aka {group.Key.HookId}");
			AppendLine(builder, indent + 4, $"case {group.Key.HookId}:");
			AppendLine(builder, indent + 4, "{");

			var orderedMethods = group
				.OrderByDescending(static method => method.Score)
				.ThenBy(static method => method.MethodName, StringComparer.Ordinal)
				.ToList();

			for (var methodIndex = 0; methodIndex < orderedMethods.Count; methodIndex++)
			{
				AppendMethodInvocation(builder, orderedMethods[methodIndex], methodIndex, indent + 5);
			}

			AppendLine(builder, indent + 5, "break;");
			AppendLine(builder, indent + 4, "}");
		}

		AppendLine(builder, indent + 3, "}");
		AppendLine(builder, indent + 2, "}");
		AppendLine(builder, indent + 2, "catch (global::System.Exception ex)");
		AppendLine(builder, indent + 2, "{");
		AppendLine(builder, indent + 3,
			$"global::Carbon.Logger.Error(string.Format(\"Failed to call internal hook '{{0}}' on {model.BaseKind} '{{1}} v{{2}}' [{{3}}]\", global::Carbon.Pooling.HookStringPool.GetOrAdd(hook), {model.VersionOwnerExpression}.Name, {model.VersionOwnerExpression}.Version, hook), ex);");
		AppendLine(builder, indent + 3, "OnException(hook);");
		AppendLine(builder, indent + 2, "}");
		AppendLine(builder, indent + 2, "return null;");
		AppendLine(builder, indent + 1, "}");
		AppendLine(builder, indent, "}");
	}

	private static void AppendMethodInvocation(StringBuilder builder, InternalCallHookMethodModel method, int methodIndex, int indent)
	{
		if (!string.IsNullOrWhiteSpace(method.ConditionalSymbol))
		{
			AppendLine(builder, indent, $"#if {method.ConditionalSymbol}");
		}

		var conditions = new List<string>(method.Parameters.Count);
		var arguments = new List<string>(method.Parameters.Count);

		for (var parameterIndex = 0; parameterIndex < method.Parameters.Count; parameterIndex++)
		{
			var parameter = method.Parameters[parameterIndex];
			var argName = $"arg{parameterIndex}_{methodIndex}";
			var guardName = $"narg{parameterIndex}_{methodIndex}";

			if (parameter.IsOut)
			{
				arguments.Add($"out var {argName}");
				continue;
			}

			if (parameter.UseInlineDefaultExpression)
			{
				arguments.Add($"narg{parameterIndex} is {parameter.TypeName} {argName} ? {argName} : ({parameter.TypeName})default");
				continue;
			}

			AppendLine(builder, indent, $"var {guardName} = narg{parameterIndex} is {parameter.TypeName} or null;");
			AppendLine(builder, indent,
				$"var {argName} = {guardName} ? ({parameter.TypeName})(narg{parameterIndex} ?? ({parameter.TypeName})default) : ({parameter.TypeName})default;");

			if (parameter.RequiresGuard)
			{
				conditions.Add(guardName);
			}

			arguments.Add(parameter.IsRef ? $"ref {argName}" : argName);
		}

		if (conditions.Count > 0)
		{
			AppendLine(builder, indent, $"if ({string.Join(" && ", conditions)})");
			AppendLine(builder, indent, "{");
		}

		var callIndent = indent + (conditions.Count > 0 ? 1 : 0);
		AppendLine(builder, callIndent, $"{(method.ReturnsVoid ? string.Empty : "return ")}{method.MethodName}({string.Join(", ", arguments)});");

		for (var parameterIndex = 0; parameterIndex < method.Parameters.Count; parameterIndex++)
		{
			var parameter = method.Parameters[parameterIndex];
			if (!parameter.IsRef && !parameter.IsOut)
			{
				continue;
			}

			AppendLine(builder, callIndent, $"args[{parameterIndex}] = arg{parameterIndex}_{methodIndex};");
		}

		if (method.ReturnsVoid)
		{
			AppendLine(builder, callIndent, "return null;");
		}

		if (conditions.Count > 0)
		{
			AppendLine(builder, indent, "}");
		}

		if (!string.IsNullOrWhiteSpace(method.ConditionalSymbol))
		{
			AppendLine(builder, indent, "#endif");
		}
	}

	private static string NormalizeUsing(string value)
	{
		if (string.IsNullOrWhiteSpace(value))
		{
			return string.Empty;
		}

		value = value.Trim().TrimEnd(';');
		if (value.StartsWith("global ", StringComparison.Ordinal))
		{
			value = value.Substring("global ".Length).TrimStart();
		}

		if (value.StartsWith("using ", StringComparison.Ordinal))
		{
			value = value.Substring("using ".Length);
		}

		return value.Trim();
	}

	private static void AppendLine(StringBuilder builder, int indent, string line)
	{
		for (var index = 0; index < indent; index++)
		{
			builder.Append('\t');
		}

		builder.AppendLine(line);
	}
}
