name: Common Test Runner

on:
  workflow_call:
    inputs:
      IDENTIFIER:
        required: true
        type: string
    secrets:
      PAT_ALL_REPO:
        required: true

jobs:
  configure:
    name: Configure Test (${{ inputs.IDENTIFIER }})
    runs-on: ubuntu-latest
    outputs:
      download_id: ${{ steps.config.outputs.download_id }}
      rust_branch: ${{ steps.config.outputs.rust_branch }}
      build_config: ${{ steps.config.outputs.build_config }}
    steps:
      - id: config
        shell: bash
        run: |
          REF="${{ inputs.IDENTIFIER }}"
          
          BUILD_CONFIG="Debug"
          RUST_BRANCH="public"

          case "$REF" in
            "develop")
              DOWNLOAD_ID="edge_build"
              ;;
            "preview")
              DOWNLOAD_ID="preview_build"
              ;;
            "qa")
              DOWNLOAD_ID="qa_build"
              RUST_BRANCH="staging"
              ;;
            "production")
              DOWNLOAD_ID="production_build"
              BUILD_CONFIG="Release"
              ;;
            "rust_beta/aux01")
              DOWNLOAD_ID="rustbeta_aux01_build"
              RUST_BRANCH="aux01-staging"
              ;;
            "rust_beta/aux02")
              DOWNLOAD_ID="rustbeta_aux02_build"
              RUST_BRANCH="aux02"
              ;;
            "rust_beta/aux03")
              DOWNLOAD_ID="rustbeta_aux03_build"
              RUST_BRANCH="aux03"
              ;;
            "rust_beta/staging")
              DOWNLOAD_ID="rustbeta_staging_build"
              RUST_BRANCH="staging"
              ;;
            "rust_beta/release")
              DOWNLOAD_ID="rustbeta_release_build"
              RUST_BRANCH="release"
              ;;
            *)
              echo "Unknown branch ref: $REF"
              exit 1
              ;;
          esac

          echo "download_id=$DOWNLOAD_ID" >> $GITHUB_OUTPUT
          echo "rust_branch=$RUST_BRANCH" >> $GITHUB_OUTPUT
          echo "build_config=$BUILD_CONFIG" >> $GITHUB_OUTPUT

  test:
    name: Test Runner
    needs: configure
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Git Clone
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_ALL_REPO }}
          submodules: recursive

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: 'Carbon.Core/Carbon.TestRunner/**/*.csproj'
          dotnet-version: |
            10.0.x

      - name: DotNet Restore
        shell: bash
        run: |
          dotnet restore Carbon.Core/Carbon.TestRunner

      - name: DotNet Build
        shell: bash
        run: |
          dotnet build Carbon.Core/Carbon.TestRunner -c Release --no-restore

      - name: Run Tests
        shell: bash
        env:
          WorkingDir: TestRunner
          BranchName: ${{ needs.configure.outputs.rust_branch }}
          CarbonDownloadZipUrl: https://github.com/CarbonCommunity/Carbon/releases/download/${{ needs.configure.outputs.download_id }}/Carbon.Linux.${{ needs.configure.outputs.build_config }}.tar.gz
          ForDebug__SkipRustServerIfPresent: false
          ForDebug__NoRustServerRun: false
          ENV_BASE_DIR: ${{ github.workspace }}/TestRunner/RustInstance
          TERM: xterm
          DOORSTOP_ENABLED: 1
          DOORSTOP_TARGET_ASSEMBLY: ${{ github.workspace }}/TestRunner/RustInstance/carbon/managed/Carbon.Preloader.dll
          RUST_LD_PRELOAD: ${{ github.workspace }}/TestRunner/RustInstance/libdoorstop.so
          RUST_LD_LIBRARY_PATH: ${{ github.workspace }}/TestRunner/RustInstance:${{ github.workspace }}/TestRunner/RustInstance/RustDedicated_Data/Plugins/x86_64
        run: |
          dotnet run --project Carbon.Core/Carbon.TestRunner -c Release --no-build
