name: Edge Build
concurrency:
  group: build-edge
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
    paths-ignore:
      - ".github/**/*"
      - "**/*.md"
      - "src/Carbon.Tests/**/*"
      - ".gitignore"

jobs:
  call-common:
    uses: ./.github/workflows/common-build.yml
    name: Build
    permissions:
      contents: write
    with:
      # noinspection UndefinedParamsPresent
      GIT_BRANCH: main
      # noinspection UndefinedParamsPresent
      RELEASE_BODY: |
        This is a development build of Carbon based on the latest commit pushed to the repository (`main` branch).
        Use this build on the `release` Rust server branch.

        This build is targeted at developers.
        The general public is advised to use the [stable] build. Use the [experimental] build if you want to test out major changes before they are merged into `main` and released on a stable build.
        
        ### How to install
        1. Download the `Carbon.[Windows|Linux].Debug` archive from the attachments below.
        2. Unzip the archive to the root of your Rust Dedicated Server.
        3. Restart the server and enjoy.
        
        [stable]: https://github.com/CarbonCommunity/Carbon/releases/latest
        [experimental]: https://github.com/CarbonCommunity/Carbon/releases/experimental_build
    secrets:
      PAT_ALL_REPO: ${{ secrets.PAT_ALL_REPO }}
      VERSIONS_TOKEN: ${{ secrets.VERSIONS_TOKEN }}

  call-tests:
    uses: ./.github/workflows/common-test.yml
    needs: call-common
    name: Tests
    with:
      build_identifier: 'main'
