name: Edge Test
concurrency: test-edge

on:
  workflow_dispatch:

jobs:
  call-common:
    uses: ./.github/workflows/common-test.yml
    name: Call Common Test
    with:
      # noinspection UndefinedParamsPresent
      IDENTIFIER: develop
