name: Production Build
concurrency: build-production

on:
  workflow_dispatch:

jobs:
  call-common:
    uses: ./.github/workflows/common-build.yml
    name: Build
    permissions:
      contents: write
    with:
      # noinspection UndefinedParamsPresent
      GIT_BRANCH: production
      # noinspection UndefinedParamsPresent
      RELEASE_BODY: |
        This is a release build of Carbon based on the `production` branch.
        This build is targeted at the general public.

        ### How to install
        1. Download the `Carbon.[Windows|Linux].Release` archive from the attachments below.
        2. Unzip the archive to the root of your Rust Dedicated Server.
        3. Restart the server and enjoy.
    secrets:
      PAT_ALL_REPO: ${{ secrets.PAT_ALL_REPO }}
      VERSIONS_TOKEN: ${{ secrets.VERSIONS_TOKEN }}
      NUGET_API: ${{ secrets.NUGET_API }}
