name: Profiler Build
concurrency: build-profiler

on:
  workflow_dispatch:

jobs:
  build:
    name: Profiler Build
    runs-on: ubuntu-latest
    container: rust:bullseye
    continue-on-error: false

    outputs:
      date: ${{ steps.step1.outputs.date }}
      clock: ${{ steps.step1.outputs.clock }}
      tag: ${{ steps.step1.outputs.tag }}
      ref: ${{ steps.step1.outputs.ref }}
      version: ${{ steps.step1.outputs.version }}

    steps:
      - name: Git Clone
        uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ secrets.PAT_ALL_REPO }}
          submodules: recursive

      - name: Environment Setup
        id: step1
        shell: bash
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "clock=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "tag=$(date +'%Yd%j')" >> $GITHUB_OUTPUT
          echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=2.8.$(curl -s -L 'https://carbonmod.gg/version?id=profiler&token=${{secrets.VERSIONS_TOKEN}}')" >> $GITHUB_OUTPUT
          git config --global --add safe.directory /__w/Carbon/Carbon
         
      - name: Rust Setup
        shell: bash
        run: |
          apt update
          apt install -y mingw-w64
          
          rustup install stable
          rustup default stable
          rustup target add x86_64-pc-windows-gnu
          rustup component add rust-std --target x86_64-pc-windows-gnu
          rustup show
          rustc --print sysroot
          
          which x86_64-w64-mingw32-dlltool || echo "dlltool not found"
          x86_64-w64-mingw32-dlltool --version
  
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.406

      - name: Carbon.Native Toolchain
        uses: dtolnay/rust-toolchain@stable
  
      - name: Carbon.Native Build (Linux)
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: -r --target x86_64-unknown-linux-gnu
          directory: Carbon.Core/Carbon.Native
          
      - name: Carbon.Native Build (Windows)
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: -r --target x86_64-pc-windows-gnu
          directory: Carbon.Core/Carbon.Native
  
      - name: Carbon Bootstrap
        shell: bash
        run: |
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/bootstrap.cr
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/update.cr

      - name: Profiler Build
        shell: bash
        run: |
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/profiler.cr
      
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-develop-linux
          path: |
            Release/Carbon.Linux.Profiler.tar.gz
            Release/Carbon.Windows.Profiler.zip
            
  release-on-commit:
    name: Profiler Release
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - name: 🗑️ Delete existing release tag
        uses: dev-drprasad/delete-tag-and-release@92d94d77429cb0436597047a92369526a5824f50
        with:
          delete_release: true
          tag_name: profiler_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💤 Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: Release

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Release

      - name: 🏷️ Update release tag
        uses: softprops/action-gh-release@a92196038060e0c673cf3ba5b98710dd716731df
        with:
          draft: false
          prerelease: true
          tag_name: profiler_build
          name: "Profiler Build — v${{ needs.build.outputs.version }}"
          body: |
            This is an out-of-the-box build of the Carbon.Profiler dedicated to be working on vanilla and/or Oxide servers.
            Run `find carbon` upon server boot to get further command instructions.

            ### How to install
            1. Download the `Carbon.[Windows|Linux].Profiler` archive from the attachments below.
            2. Unzip the archive to the HarmonyMods directory of your Rust Dedicated Server.
            3. Start the server and enjoy, or run `harmony.load Carbon.Profiler`.
          files: |
            Release/build-develop-windows/Carbon.Windows.Profiler.zip     
            Release/build-develop-linux/Carbon.Linux.Profiler.tar.gz     
