name: Profiler Build
concurrency: build-profiler

on:
  workflow_dispatch:

jobs:
  build:
    name: Profiler Build
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        include:
          - group: Linux
            target: x86_64-unknown-linux-gnu
            build_arg: Unix
            container: "rust:bullseye"
          - group: Windows
            target: x86_64-pc-windows-gnu
            build_arg: ""

    outputs:
      version: ${{ steps.step1.outputs.version }}

    steps:
      - name: Configure Git
        shell: bash
        run: |
          git config --global fetch.parallel 0
          git config --global submodule.fetchJobs 0

      - name: Git Clone
        uses: actions/checkout@v6
        with:
          ref: develop
          token: ${{ secrets.PAT_ALL_REPO }}
          submodules: recursive

      - name: Environment Setup
        id: step1
        shell: bash
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "clock=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "tag=$(date +'%Yd%j')" >> $GITHUB_OUTPUT
          echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=2.8.$(curl -s -L 'https://api.carbonmod.gg/version?id=profiler&token=${{secrets.VERSIONS_TOKEN}}')" >> $GITHUB_OUTPUT
          git config --global --add safe.directory "*"

      - name: Install MinGW (Windows Build Only)
        if: matrix.group == 'Windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/Carbon.Native

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Carbon.Native Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Native
        working-directory: src/Carbon.Native
        shell: bash
        run: |
          cargo build -r --target ${{ matrix.target }}

      - name: Carbon Bootstrap CS
        shell: bash
        run: |
          dotnet run --project src/Carbon.Tools/Carbon.Runner tools/build/runners/bootstrap.cs

      - name: Carbon Update CS
        shell: bash
        run: |
          dotnet run --project src/Carbon.Tools/Carbon.Runner tools/build/runners/update.cs

      - name: Profiler Build
        shell: bash
        env:
          VERSION: ${{ steps.step1.outputs.version }}
        run: |
          dotnet run --project src/Carbon.Tools/Carbon.Runner tools/build/runners/profiler.cs Debug${{ matrix.build_arg }} HARMONYMOD profiler_build

      - name: Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.group }}
          path: |
            Release/Carbon.Linux.Profiler.tar.gz
            Release/Carbon.Windows.Profiler.zip

  release-on-commit:
    name: Profiler Release
    needs: [ "build" ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git Clone
        uses: actions/checkout@v6

      - name: 🗑️ Delete existing release tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete profiler_build --cleanup-tag --yes || echo "Release/Tag not found, nothing to delete"

      - name: 💤 Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: release
          merge-multiple: true

      - name: Display structure
        run: ls -R
        working-directory: release

      - name: 🏷️ Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          tag_name: profiler_build
          name: "Profiler Build — v${{ needs.build.outputs.version }}"
          body: |
            This is an out-of-the-box build of the Carbon.Profiler dedicated to be working on vanilla and/or Oxide servers.
            Run `find carbon` upon server boot to get further command instructions.

            ### How to install
            1. Download the `Carbon.[Windows|Linux].Profiler` archive from the attachments below.
            2. Unzip the archive to the HarmonyMods directory of your Rust Dedicated Server.
            3. Start the server and enjoy, or run `harmony.load Carbon.Profiler`.
          files: |
            release/Carbon.Windows.Profiler.zip
            release/Carbon.Linux.Profiler.tar.gz
