name: Rust (AUX03) Build
concurrency: build-aux03

on:
  workflow_dispatch:

  schedule:
    - cron: "00 19 * * *"

jobs:
  build:
    name: Rust (AUX03) Build
    runs-on: ubuntu-latest
    container: rust:bullseye
    continue-on-error: false

    outputs:
      date: ${{ steps.step1.outputs.date }}
      clock: ${{ steps.step1.outputs.clock }}
      tag: ${{ steps.step1.outputs.tag }}
      ref: ${{ steps.step1.outputs.ref }}
      version: ${{ steps.step1.outputs.version }}

    steps:   
      - name: Git Clone
        uses: actions/checkout@v3
        with:
          ref: rust_beta/aux03
          token: ${{ secrets.PAT_ALL_REPO }}
          submodules: recursive
          
      - name: Environment Setup
        id: step1
        shell: bash
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "clock=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "tag=$(date +'%Yd%j')" >> $GITHUB_OUTPUT
          echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=2.7.$(curl -s -L 'https://carbonmod.gg/version?id=aux03&token=${{secrets.VERSIONS_TOKEN}}')" >> $GITHUB_OUTPUT
          git config --global --add safe.directory /__w/Carbon/Carbon
          
      - name: Rust Setup
        shell: bash
        run: |
          apt update
          apt install -y mingw-w64
          
          rustup install stable
          rustup default stable
          rustup target add x86_64-pc-windows-gnu
          rustup component add rust-std --target x86_64-pc-windows-gnu
          rustup show
          rustc --print sysroot
          
          which x86_64-w64-mingw32-dlltool || echo "dlltool not found"
          x86_64-w64-mingw32-dlltool --version

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.406
          
      - name: Carbon.Native Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Carbon.Native Build (Linux)
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: -r --target x86_64-unknown-linux-gnu
          directory: Carbon.Core/Carbon.Native
          
      - name: Carbon.Native Build (Windows)
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: -r --target x86_64-pc-windows-gnu
          directory: Carbon.Core/Carbon.Native

      - name: Carbon Bootstrap
        shell: bash
        run: |
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/bootstrap.cr
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/update.cr aux03

      - name: Carbon Build
        shell: bash
        run: |
          export VERSION=${{ steps.step1.outputs.version }}
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr Debug RUST_AUX03 rustbeta_aux03_build
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr DebugUnix RUST_AUX03 rustbeta_aux03_build
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr Minimal RUST_AUX03 rustbeta_aux03_build
          dotnet run --project Carbon.Core/Carbon.Tools/Carbon.Runner Tools/Build/runners/build.cr MinimalUnix RUST_AUX03 rustbeta_aux03_build

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            Release/Carbon.Linux.Debug.tar.gz
            Release/Carbon.Linux.Debug.info
            Release/Carbon.Linux.Minimal.tar.gz
            Release/Carbon.Linux.Minimal.info
            Release/Carbon.Windows.Debug.zip
            Release/Carbon.Windows.Debug.info
            Release/Carbon.Windows.Minimal.zip
            Release/Carbon.Windows.Minimal.info

  release-on-commit:
    name: Rust (AUX03) Release
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - name: 🗑️ Delete existing release tag
        uses: dev-drprasad/delete-tag-and-release@92d94d77429cb0436597047a92369526a5824f50
        with:
          delete_release: true
          tag_name: rustbeta_aux03_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💤 Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: ⬇️ Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: Release

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Release

      - name: 🏷️ Update release tag
        uses: softprops/action-gh-release@a92196038060e0c673cf3ba5b98710dd716731df
        with:
          draft: false
          prerelease: true
          tag_name: rustbeta_aux03_build
          name: "Rust (AUX03) Build — v${{ needs.build.outputs.version }}"
          body: |
            This is a manually triggered development build of Carbon based on the `rust_beta/aux03` branch.
            This build might and probably will be very unstable and its sole purpose is for testing and/or exploring Rust's future update features in a modded environment.
                    
            This build is targeted at developers or testers.
            The general public is advised to use one of the [stable] builds.
            Since it's manually triggered, we're confident you should use this build to test out the latest Carbon changes.

            ### How to install
            1. Download the `Carbon.[Windows|Linux].Debug` archive from the attachments below.
            2. Unzip the archive to the root of your Rust Dedicated Server.
            3. Restart the server and enjoy.

            [stable]: https://github.com/CarbonCommunity/Carbon.Core/releases/latest
          files: |
            Release/build/Carbon.Linux.Debug.info
            Release/build/Carbon.Linux.Debug.tar.gz
            Release/build/Carbon.Linux.Minimal.info
            Release/build/Carbon.Linux.Minimal.tar.gz
            Release/build/Carbon.Windows.Debug.info
            Release/build/Carbon.Windows.Debug.zip     
            Release/build/Carbon.Windows.Minimal.info
            Release/build/Carbon.Windows.Minimal.zip
